-- Note: File size and mime type restrictions cannot be set via SQL migration
-- because the storage.buckets table is managed internally by Supabase.
-- These restrictions must be configured via the Supabase Dashboard or Storage API.
--
-- Recommended configuration for the profile-pictures bucket:
--   File size limit: 5 MB (5242880 bytes)
--   Allowed MIME types: image/jpeg, image/png, image/webp, image/heic
--
-- Steps to apply:
--   1. Go to Supabase Dashboard > Storage
--   2. Click on the "profile-pictures" bucket > Edit
--   3. Set:
--      - File size limit: 5242880
--      - Allowed MIME types: image/jpeg,image/png,image/webp,image/heic
--
-- Client-side enforcement already exists via ImageSourcePicker._allowedExtensions.
-- Server-side enforcement is required to prevent upload abuse.
--
-- Current status: PENDING — restrictions have not yet been applied via Dashboard.
